### PR TITLE
Fix wadler nest

### LINKED ISSUE #20: Converge the Wadler API to what we have in ruby/prettyprint
- [ ] nest

### PR DESCRIPTION
**Pull request by Amine-Mike**
fixes: https://github.com/Faveod/oppen-ruby/issues/20

### CODE REVIEW

**Review by stackmystack — CHANGES_REQUESTED** [review]
commit messages:

1. `fix: converge nest comportment to ruby/PrettyPrint` -> `wadler: nest: be iso with ruby/prettyprint`

File: lib/oppen/print_stack.rb [hunk 1]
```diff
@@ -130,11 +130,23 @@ def handle_break(token, token_length)
...
       in Token::BreakType::CONSISTENT
         @space = block.offset - token.offset
-        print_new_line margin - space
+        indentation =
+          if config&.indent_anchor == Config::IndentAnchor::ON_BEGIN
+            token.offset
+          else
+            margin - space
+          end
+        print_new_line indentation
```
Comment (stackmystack) [inline lib/oppen/print_stack.rb]:
```suggestion
        indent =
          if config&.indent_anchor == Config::IndentAnchor::ON_BEGIN
            token.offset
          else
            margin - space
          end
        print_new_line indent
```

File: lib/oppen/print_stack.rb [hunk 2]
```diff
@@ -130,11 +130,23 @@ def handle_break(token, token_length)
...
         if token_length > space
           @space = block.offset - token.offset
-          print_new_line margin - space
+          indentation =
+            if config&.indent_anchor == Config::IndentAnchor::ON_BEGIN
+              token.offset
+            else
+              margin - space
+            end
+          print_new_line indentation
```
Comment (stackmystack) [inline lib/oppen/print_stack.rb]:
```suggestion
          indent =
            if config&.indent_anchor == Config::IndentAnchor::ON_BEGIN
              token.offset
            else
              margin - space
            end
          print_new_line indent
```

File: lib/oppen/printer.rb [hunk 3]
```diff
@@ -138,6 +140,11 @@ def handle_end(token)
         tokens[right] = token
         size[right] = -1
         scan_stack.push right
+        if config&.indent_anchor == Config::IndentAnchor::ON_BEGIN &&
```
Comment (stackmystack) [inline lib/oppen/printer.rb]: We should have a separate config for this one, a boolean.

File: lib/oppen/printer.rb [hunk 4]
```diff
@@ -138,6 +140,11 @@ def handle_end(token)
...
+           (!scan_stack.empty? && right_total - left_total < print_stack.space)
```
Comment (stackmystack) [inline lib/oppen/printer.rb:144]: Maybe we should extract this to a separate function that expresses the intended meaning pf this check?

File: lib/wadler/print.rb [hunk 5]
```diff
@@ -39,43 +39,41 @@ def output
...
+      @current_indent += indent
 
       raise LocalJumpError if !block_given?
 
       block.call
 
-      tokens << Oppen.end
-      @current_indent = previous_indent
+      @current_indent -= indent
     end
```
Comment (stackmystack) [inline lib/wadler/print.rb]: That might be dangerous:

On one hand, we're advancing `@current_indent`, and then we might raise an exception.
When that happens, we don't decrease it back again, and we're in a bad state.

Use [`ensure`](https://ruby-doc.org/docs/ruby-doc-bundle/UsersGuide/rg/ensure.html)

File: lib/oppen.rb [hunk 6]
```diff
@@ -39,9 +39,12 @@ module IndentAnchor
     end
 
     attr_accessor :indent_anchor
+    # @return [Boolean] Determine if we print a group on the line on End Token
```
Comment (stackmystack) [inline lib/oppen.rb]: Very vague, can't understand what you mean + use imperative tone.

File: lib/oppen.rb [hunk 7]
```diff
@@ -52,8 +55,8 @@ def self.oppen
 
     # Default config for Wadler usage
     # @return [Config]
-    def self.wadler
-      new(indent_anchor: IndentAnchor::ON_BEGIN)
+    def self.wadler(eager_print: false)
+      new(indent_anchor: IndentAnchor::ON_BEGIN, eager_print:)
```
Comment (stackmystack) [inline lib/oppen.rb]: But wadler needs `eager_print: true`, no?

**Review by stackmystack — APPROVED** [review]
